version: "3.2"
services:
    nginx: 
        build: nginx
        container_name: ${COMPOSE_PROJECT_NAME}-nginx
        restart: always
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - code_source:/www
    php: 
        build: php
        container_name: ${COMPOSE_PROJECT_NAME}-php
        restart: always
        volumes:
            - code_source:/www
    redis: 
        build: redis
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        restart: always
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis/data:/data
        command: ["redis-server","/usr/local/etc/redis/redis.conf"]
      


volumes:
    code_source:
      driver_opts:
        type: none
        device: ${PROJECT_DIR}
        o: bind




