version: "3.2"
services:
    nginx: 
        build: nginx
        container_name: nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - code_source:/www
    php: 
        build: php
        container_name: php
        restart: always
        volumes:
            - code_source:/www
    redis: 
        build: redis
        container_name: redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis/data:/data
        command: ["redis-server","/usr/local/etc/redis/redis.conf"]
      


volumes:
    code_source:
      driver_opts:
        type: none
        device: /home/crusj/Project/laravel
        o: bind




